const entries = [
  {
    country: 'Sverige',
    song: 'My System',
    artist: 'FELICIA',
    id: 1,
    code: 'se',
    youtube: 'https://www.youtube.com/watch?v=W7AZN_me8eA',
  },
  {
    country: 'Israel',
    song: 'Michelle',
    artist: 'Noam Bettan',
    id: 2,
    code: 'il',
    youtube: 'https://www.youtube.com/watch?v=j2uPlJndByI',
  },
  /*{
          country: 'Nederländerna',
          song: 'C’est la vie',
          artist: 'Claude',
          id: 3,
          code: 'nl',
        },*/
  {
    country: 'San Marino',
    song: 'Superstar',
    artist: 'Senhit',
    id: 4,
    code: 'sm',
    youtube: 'https://www.youtube.com/watch?v=tC3eHYO38do',
  },
  /*{
          country: 'Spanien',
          song: 'Esa diva',
          artist: 'Melody',
          id: 5,
          code: 'es',
        },*/
  // {
  //   country: 'Slovenien',
  //   song: 'How Much Time Do We Have Left',
  //   artist: 'Klemen',
  //   id: 6,
  //   code: 'si',
  // },
  {
    country: 'Tyskland',
    song: 'Fire',
    artist: 'Sarah Engels',
    id: 7,
    code: 'de',
    youtube: 'https://www.youtube.com/watch?v=8zjFGH4_Te8',
  },
  {
    country: 'Luxemburg',
    song: 'Mother Nature',
    artist: 'Eva Marija',
    id: 8,
    code: 'lu',
    youtube: 'https://www.youtube.com/watch?v=4WA162bl1Fo',
  },
  {
    country: 'Storbritannien',
    song: 'Eins, Zwei, Drei',
    artist: 'Look Mum No Computer',
    id: 9,
    code: 'gb',
    youtube: 'https://www.youtube.com/watch?v=8XR2RvfZ-68',
  },
  {
    country: 'Frankrike',
    song: 'Regarde!',
    artist: 'Monroe',
    id: 10,
    code: 'fr',
    youtube: 'https://www.youtube.com/watch?v=f1RDzzLzFBs',
  },
  {
    country: 'Cypern',
    song: 'Jalla',
    artist: 'Antigoni',
    id: 11,
    code: 'cy',
    youtube: 'https://www.youtube.com/watch?v=TzSs51BiQrE',
  },
  {
    country: 'Armenien',
    song: 'Paloma Rumba',
    artist: 'Simón',
    id: 12,
    code: 'am',
    youtube: 'https://www.youtube.com/watch?v=5EXoK-lgocw',
  },
  {
    country: 'Serbien',
    song: 'Kraj mene',
    artist: 'Lavina',
    id: 13,
    code: 'rs',
    youtube: 'https://www.youtube.com/watch?v=931yYfZH2F8',
  },
  {
    country: 'Norge',
    song: 'Ya ya ya',
    artist: 'Jonas Lovv',
    id: 14,
    code: 'no',
    youtube: 'https://www.youtube.com/watch?v=MasllzWk_bQ',
  },
  {
    country: 'Schweiz',
    song: 'Alice',
    artist: 'Veronica Fusaro',
    id: 15,
    code: 'ch',
    youtube: 'https://www.youtube.com/watch?v=PfpYGAzW5dM',
  },
  {
    country: 'Österrike',
    song: 'Tanzschein',
    artist: 'Cosmó',
    id: 16,
    code: 'at',
    youtube: 'https://www.youtube.com/watch?v=IPvJbGy5_o0',
  },
  // {
  //   country: 'Irland',
  //   song: 'Laika Party',
  //   artist: 'Emmy',
  //   id: 17,
  //   code: 'ie',
  // },
  {
    country: 'Litauen',
    song: 'Sólo quiero más',
    artist: 'Lion Ceccah',
    id: 18,
    code: 'lt',
    youtube: 'https://www.youtube.com/watch?v=mPZMHqSsoeo',
  },
  {
    country: 'Grekland',
    song: 'Ferto',
    artist: 'Akylas',
    id: 19,
    code: 'gr',
    youtube: 'https://www.youtube.com/watch?v=VlwIKCFYQyw',
  },
  {
    country: 'Danmark',
    song: 'Før vi går hjem',
    artist: 'Søren Torpegaard Lund',
    id: 20,
    code: 'dk',
    youtube: 'https://www.youtube.com/watch?v=vKCsNbrt5yI',
  },
  {
    country: 'Italien',
    song: 'Per sempre sì',
    artist: 'Sal Da Vinci',
    id: 21,
    code: 'it',
    youtube: 'https://www.youtube.com/watch?v=kA7pS6kaTpg',
  },
  {
    country: 'Finland',
    song: 'Liekinheitin',
    artist: 'Linda Lampenius & Pete Parkkonen',
    id: 22,
    code: 'fi',
    youtube: 'https://www.youtube.com/watch?v=GS91CAAddZA',
  },
  {
    country: 'Belgien',
    song: 'Dancing on the Ice',
    artist: 'Essyla',
    id: 23,
    code: 'be',
    youtube: 'https://www.youtube.com/watch?v=9sfI4g6DWTU',
  },
  {
    country: 'Montenegro',
    song: 'Nova zora',
    artist: 'Tamara Živković',
    id: 24,
    code: 'me',
    youtube: 'https://www.youtube.com/watch?v=6TfmkUXeKf0',
  },
  {
    country: 'Lettland',
    song: 'Ēnā',
    artist: 'Atvara',
    id: 25,
    code: 'lv',
    youtube: 'https://www.youtube.com/watch?v=ylj-kHKEFMY',
  },
  {
    country: 'Albanien',
    song: 'Nân',
    artist: 'Alis',
    id: 26,
    code: 'al',
    youtube: 'https://www.youtube.com/watch?v=rZuF1aDDxKE',
  },
  {
    country: 'Portugal',
    song: 'Rosa',
    artist: 'Bandidos do Cante',
    id: 27,
    code: 'pt',
    youtube: 'https://www.youtube.com/watch?v=8emG9PghYXg',
  },
  {
    country: 'Polen',
    song: 'Pray',
    artist: 'Alicja',
    id: 28,
    code: 'pl',
    youtube: 'https://www.youtube.com/watch?v=bWgdnuww4eY',
  },
  {
    country: 'Azerbajdzjan',
    song: 'Nova zora',
    artist: 'Tamara Živković',
    id: 29,
    code: 'az',
    youtube: 'https://www.youtube.com/watch?v=iMDBPe25JhM',
  },
  {
    country: 'Ukraina',
    song: 'Ridnym',
    artist: 'Leléka',
    id: 30,
    code: 'ua',
    youtube: 'https://www.youtube.com/watch?v=qxEeWgjbxx0',
  },
  {
    country: 'Georgien',
    song: 'On Replay',
    artist: 'Bzikebi',
    id: 31,
    code: 'ge',
    youtube: 'https://www.youtube.com/watch?v=coh-lygCINY',
  },
  /*{
          country: 'Island',
          song: 'Róa',
          artist: 'Væb',
          id: 32,
          code: 'is',
        },*/
  {
    country: 'Estland',
    song: 'Too Epic To Be True',
    artist: 'Vanilla Ninja',
    id: 33,
    code: 'ee',
    youtube: 'https://www.youtube.com/watch?v=pf-oPWrkXFw',
  },
  {
    country: 'Kroatien',
    song: 'Andromeda',
    artist: 'Lelek',
    id: 34,
    code: 'hr',
    youtube: 'https://www.youtube.com/watch?v=5JXpBZgiHkY',
  },
  {
    country: 'Australien',
    song: 'Eclipse',
    artist: 'Delta Goodrem',
    id: 35,
    code: 'au',
    youtube: 'https://www.youtube.com/watch?v=KsFY11nOQDo',
  },
  {
    country: 'Tjeckien',
    song: 'Crossroads',
    artist: 'Daniel Žižka',
    id: 36,
    code: 'cz',
    youtube: 'https://www.youtube.com/watch?v=6ea25aRGpLo',
  },
  {
    country: 'Malta',
    song: 'Bella',
    artist: 'Aidan',
    id: 37,
    code: 'mt',
    youtube: 'https://www.youtube.com/watch?v=YA7Ku_P59Dk',
  },
  {
    country: 'Moldavien',
    song: 'Viva, Moldova',
    artist: 'Satoshi',
    id: 38,
    code: 'md',
    youtube: 'https://www.youtube.com/watch?v=k340WWX6zHk',
  },
  {
    country: 'Rumänien',
    song: 'Choke Me',
    artist: 'Alexandra Căpitănescu',
    id: 39,
    code: 'ro',
    youtube: 'https://www.youtube.com/watch?v=f2byUc4L9wo',
  },
  {
    country: 'Bulgarien',
    song: 'Bangaranga',
    artist: 'Dara',
    id: 40,
    code: 'bg',
    youtube: 'https://www.youtube.com/watch?v=_pkC9J6BPFY',
  },
];
